### ISSUE TITLE
Original memory requests/limits values are incorrect on the grafana dashboard

### ISSUE THREAD

**Issue by chandrams** [kruize/kruize#151]
**Describe the bug**
Original memory requests/limits values are incorrect on the grafana dashboard

**To Reproduce**
Steps to reproduce:
- Deploy kruize using the below command:
./deploy.sh -ac docker -i chandra25ms/kruize:0.6.6 

- Deploy acmeair or any application by specifying cpu/memory requests
 memory: 500M
 cpu: 2
 limits:
 memory: 1024M
 cpu: 3

I have attached the screenshot, the values for acmeair shown are 500B and 1kB instead of 500M and 1024M

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Kubernetes Environment Minikube
**Additional context**

**Comment by chandrams** [comment]
![Screenshot_2020-07-14 Kruize Dashboard - Grafana](https://user-images.githubusercontent.com/9799411/87431613-84e52500-c604-11ea-8d12-6185e4b78c0f.png)

**Comment by chandrams** [comment]
From acmeair.yaml

```
        resources:
          requests:
            memory: 500M
            cpu: 2
          limits:
            memory: 1024M
            cpu: 3
```
